
// JavaScript код с созданием переменных
/*Автор
Клименко Алина Алексеевна*/

const myName="Алина";
const mySurnane="Клименко";
const myFavoriteDrink="Чай";
const myFavoriteAnimals= "Котик";
const myFavoriteProgrammingLanguage="AAAAAAAAAA"
console.log(myName) 
console.log(mySurnane)
console.log(myFavoriteDrink)
console.log(myFavoriteAnimals)
console.log(myFavoriteProgrammingLanguage)    